//app/head.tsx
export default function Head() {
  return (
    <>
      <title>CV Person Card</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      {/* Preconnect for Google Fonts */}
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="anonymous"
      />

      {/* Google Fonts */}
      <link
        href="https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Ponomar&family=Bebas+Neue&family=Bungee+Tint&family=Rubik+Glitch&display=swap"
        rel="stylesheet"
      />

      {/* Font Awesome */}
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      />
    </>
  );
}
