export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      {/* Preconnect for Google Fonts */}
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="anonymous"
      />

      {/* Google Fonts: Ponomar, Bebas Neue, Bungee Tint, Rubik Glitch */}
      <link
        href="https://fonts.googleapis.com/css2?family=Ponomar&family=Bebas+Neue&family=Bungee+Tint&family=Rubik+Glitch&display=swap"
        rel="stylesheet"
      />

      {/* External CSS for W3.CSS */}
      <link
        rel="stylesheet"
        href="https://www.w3schools.com/w3css/4/w3.css"
      />

      {/* External Font Awesome CSS (use latest v6 if needed, here using 4.7.0 as example) */}
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
      />
    </>
  );
}
